### PR TITLE
Move summary of indonesia outside the tab

### PR DESCRIPTION
**Pull request by papank-sapar**

### CODE REVIEW

**Comment by papank-sapar** [comment]
image
Like this what you mean?

**Comment by papank-sapar** [comment]
image

How about this? I added badge on percentage

**Comment by pararang** [comment]
> image
> 
> How about this? I added badge on percentage

it is a good adjustment. but that now what I mean, in that cards, there is still open space on the right side.
Screenshot from 2020-03-29 13-40-00
can we utilize that free space with widening the three cards?

**Comment by papank-sapar** [comment]
image
Like this?

image
On mobile view

**Comment by pararang** [comment]
> image
> 
> Like this?
> image
> 
> On mobile view

Yes

**Comment by papank-sapar** [comment]
Okay..

**Pull request merged**
